import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1777305017908 implements MigrationInterface {
    name = 'Init1777305017908'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "user"."users_role_enum" AS ENUM('USER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user"."users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "email" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "firstName" character varying(50), "lastName" character varying(50), "role" "user"."users_role_enum" NOT NULL DEFAULT 'USER', "emailVerified" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."accounting" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "is_prepaid" boolean NOT NULL DEFAULT false, "is_collect" boolean NOT NULL DEFAULT false, "reference_number" character varying NOT NULL, "currency" character varying NOT NULL, "chgs_code" character varying NOT NULL, "wt_val_ppd" boolean NOT NULL DEFAULT false, "wt_val_coll" boolean NOT NULL DEFAULT false, "other_ppd" boolean NOT NULL DEFAULT false, "other_coll" boolean NOT NULL DEFAULT false, "declared_value_carriage" numeric(10,2) NOT NULL, "declared_value_customs" numeric(10,2) NOT NULL, "insurance_amt" numeric(10,2) NOT NULL, "mawbId" integer, CONSTRAINT "REL_7f71ae40d967d67c8ce5f1083f" UNIQUE ("mawbId"), CONSTRAINT "PK_6a6f4091126bfca1743ad2eb14f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."dimension" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "length" double precision NOT NULL, "width" double precision NOT NULL, "height" double precision NOT NULL, "mawbId" integer, CONSTRAINT "PK_653e621826a32965348bd4faff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."agent" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "agent_name" character varying NOT NULL, "agent_city" character varying NOT NULL, "IATA_code" character varying NOT NULL, "account_no" character varying NOT NULL, "departure" character varying NOT NULL, "to" character varying NOT NULL, "by_first_carrier" character varying NOT NULL, "second_to" character varying NOT NULL, "second_by" character varying NOT NULL, "third_to" character varying NOT NULL, "third_by" character varying NOT NULL, "destination" character varying NOT NULL, "mawbId" integer, CONSTRAINT "REL_71bb88aa3cba7812d057b2a81f" UNIQUE ("mawbId"), CONSTRAINT "PK_1000e989398c5d4ed585cf9a46f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "common"."consignee" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "name" character varying(100) NOT NULL, "email" character varying(100), "po_box_number" character varying(20), "phone_number" character varying(20), "office_number" character varying(20), "address" character varying(255) NOT NULL, "city" character varying(255) NOT NULL, "country" character varying(255) NOT NULL, CONSTRAINT "UQ_5cc009166ab66bc8ef58b8d2f58" UNIQUE ("name"), CONSTRAINT "UQ_b60abaf6980f6a979d224954083" UNIQUE ("email"), CONSTRAINT "PK_1bfdc8f4a0d0ec362948638b2a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hawb"."hawb_agent" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "agent_name" character varying NOT NULL, "agent_city" character varying NOT NULL, "IATA_code" character varying NOT NULL, "account_no" character varying NOT NULL, "departure" character varying NOT NULL, "to" character varying NOT NULL, "by_first_carrier" character varying NOT NULL, "second_to" character varying NOT NULL, "second_by" character varying NOT NULL, "third_to" character varying NOT NULL, "third_by" character varying NOT NULL, "destination" character varying NOT NULL, "hawbId" integer, CONSTRAINT "REL_1a91ef61fca2978372ce7c8f3d" UNIQUE ("hawbId"), CONSTRAINT "PK_3223deecab9b4b8249d0ccde205" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hawb"."hawb_dimension" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "length" double precision NOT NULL, "width" double precision NOT NULL, "height" double precision NOT NULL, "hawbId" integer, CONSTRAINT "PK_86d5135fabd29b985b652e7a402" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hawb"."hawb_accounting" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "is_prepaid" boolean NOT NULL DEFAULT false, "is_collect" boolean NOT NULL DEFAULT false, "chgs_code" character varying NOT NULL, "wt_val_ppd" boolean NOT NULL DEFAULT false, "wt_val_coll" boolean NOT NULL DEFAULT false, "other_ppd" boolean NOT NULL DEFAULT false, "other_coll" boolean NOT NULL DEFAULT false, "declared_value_carriage" numeric(10,2) NOT NULL, "declared_value_customs" numeric(10,2) NOT NULL, "insurance_amt" numeric(10,2) NOT NULL, "hawbId" integer, CONSTRAINT "REL_fe65cc433ed0b1b8c287e53815" UNIQUE ("hawbId"), CONSTRAINT "PK_5309510b3921548634f9fc80b15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hawb"."billing" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "weight_charge" integer NOT NULL, "valuation_charge" integer NOT NULL, "tax" integer NOT NULL, "total_charge_agent" integer NOT NULL, "total_charge_carrier" integer NOT NULL, "total" integer NOT NULL, "signature" character varying NOT NULL, "executed_date" TIMESTAMP NOT NULL, "place" character varying NOT NULL, "hawbId" integer, CONSTRAINT "REL_0abf6effe67ba32fd1d9e4969b" UNIQUE ("hawbId"), CONSTRAINT "PK_d9043caf3033c11ed3d1b29f73c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "hawb"."other_charge_type_enum" AS ENUM('AGENT', 'CARRIER')`);
        await queryRunner.query(`CREATE TABLE "hawb"."other_charge" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "type" "hawb"."other_charge_type_enum" NOT NULL, "hawbId" integer, CONSTRAINT "PK_e0e94161127fc99465345a7d04e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hawb"."hawb" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "information" character varying, "note" character varying, "no_of_pieces" integer NOT NULL, "gross_weight" numeric(10,2) NOT NULL, "unit" character varying NOT NULL, "rate_class" character varying NOT NULL, "commodity_item_no" character varying NOT NULL, "chargable_weight" numeric(10,2) NOT NULL, "rate" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "mawb_id" integer, "shipper_id" integer, "consignee_id" integer, CONSTRAINT "PK_cac9c50c5fda5e22ce3d7e77ac2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."billing" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "weight_charge" integer NOT NULL, "valuation_charge" integer NOT NULL, "tax" integer NOT NULL, "total_charge_agent" integer NOT NULL, "total_charge_carrier" integer NOT NULL, "total" integer NOT NULL, "signature" character varying NOT NULL, "executed_date" TIMESTAMP NOT NULL, "place" character varying NOT NULL, "mawbId" integer, CONSTRAINT "REL_388c399bf3f51baf94dfc013eb" UNIQUE ("mawbId"), CONSTRAINT "PK_d9043caf3033c11ed3d1b29f73c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "mawb"."other_charge_type_enum" AS ENUM('AGENT', 'CARRIER')`);
        await queryRunner.query(`CREATE TABLE "mawb"."other_charge" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "type" "mawb"."other_charge_type_enum" NOT NULL, "mawbId" integer, CONSTRAINT "PK_e0e94161127fc99465345a7d04e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."mawb" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "airline_prefix" character varying NOT NULL, "serial_no" character varying NOT NULL, "check_digit" character varying NOT NULL, "information" character varying, "note" character varying, "no_of_pieces" integer NOT NULL, "gross_weight" numeric(10,2) NOT NULL, "unit" character varying NOT NULL, "rate_class" character varying NOT NULL, "commodity_item_no" character varying NOT NULL, "chargable_weight" numeric(10,2) NOT NULL, "rate" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "shipper_id" integer, "consignee_id" integer, CONSTRAINT "PK_c35cc44afb512db73ceedfd3fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "common"."shipper" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "name" character varying(100) NOT NULL, "email" character varying(100), "po_box_number" character varying(20), "phone_number" character varying(20), "office_number" character varying(20), "address" character varying(255) NOT NULL, "city" character varying(255) NOT NULL, "country" character varying(255) NOT NULL, CONSTRAINT "UQ_69d4c9861753935d7e6b7655009" UNIQUE ("name"), CONSTRAINT "UQ_fc9acc1aab0a1db4a57ba15f2d2" UNIQUE ("email"), CONSTRAINT "PK_b83858f68f5c3acfab73b61caa5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD CONSTRAINT "FK_7f71ae40d967d67c8ce5f1083f5" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD CONSTRAINT "FK_88f20f2f77321d5538a196da671" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."agent" ADD CONSTRAINT "FK_71bb88aa3cba7812d057b2a81f2" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_agent" ADD CONSTRAINT "FK_1a91ef61fca2978372ce7c8f3de" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD CONSTRAINT "FK_60d8fa0deffbdcce6e26e2799a5" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ADD CONSTRAINT "FK_fe65cc433ed0b1b8c287e538151" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD CONSTRAINT "FK_0abf6effe67ba32fd1d9e4969b0" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."other_charge" ADD CONSTRAINT "FK_a317505aed5f953b25ef23db028" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD CONSTRAINT "FK_61f07c672ef39ccdfeaee1d392f" FOREIGN KEY ("mawb_id") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD CONSTRAINT "FK_853ed7019685c18cd666e4d8917" FOREIGN KEY ("shipper_id") REFERENCES "common"."shipper"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD CONSTRAINT "FK_083a54972a5a3925f897537250b" FOREIGN KEY ("consignee_id") REFERENCES "common"."consignee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD CONSTRAINT "FK_388c399bf3f51baf94dfc013eb8" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."other_charge" ADD CONSTRAINT "FK_c546c9a980a905c65ebea29d4bd" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD CONSTRAINT "FK_f7a8a4f65fbfe2694bfe1c16290" FOREIGN KEY ("shipper_id") REFERENCES "common"."shipper"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD CONSTRAINT "FK_6290f7f3cd6d95db6c45f3b9c01" FOREIGN KEY ("consignee_id") REFERENCES "common"."consignee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP CONSTRAINT "FK_6290f7f3cd6d95db6c45f3b9c01"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP CONSTRAINT "FK_f7a8a4f65fbfe2694bfe1c16290"`);
        await queryRunner.query(`ALTER TABLE "mawb"."other_charge" DROP CONSTRAINT "FK_c546c9a980a905c65ebea29d4bd"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP CONSTRAINT "FK_388c399bf3f51baf94dfc013eb8"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP CONSTRAINT "FK_083a54972a5a3925f897537250b"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP CONSTRAINT "FK_853ed7019685c18cd666e4d8917"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP CONSTRAINT "FK_61f07c672ef39ccdfeaee1d392f"`);
        await queryRunner.query(`ALTER TABLE "hawb"."other_charge" DROP CONSTRAINT "FK_a317505aed5f953b25ef23db028"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP CONSTRAINT "FK_0abf6effe67ba32fd1d9e4969b0"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" DROP CONSTRAINT "FK_fe65cc433ed0b1b8c287e538151"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP CONSTRAINT "FK_60d8fa0deffbdcce6e26e2799a5"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_agent" DROP CONSTRAINT "FK_1a91ef61fca2978372ce7c8f3de"`);
        await queryRunner.query(`ALTER TABLE "mawb"."agent" DROP CONSTRAINT "FK_71bb88aa3cba7812d057b2a81f2"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP CONSTRAINT "FK_88f20f2f77321d5538a196da671"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP CONSTRAINT "FK_7f71ae40d967d67c8ce5f1083f5"`);
        await queryRunner.query(`DROP TABLE "common"."shipper"`);
        await queryRunner.query(`DROP TABLE "mawb"."mawb"`);
        await queryRunner.query(`DROP TABLE "mawb"."other_charge"`);
        await queryRunner.query(`DROP TYPE "mawb"."other_charge_type_enum"`);
        await queryRunner.query(`DROP TABLE "mawb"."billing"`);
        await queryRunner.query(`DROP TABLE "hawb"."hawb"`);
        await queryRunner.query(`DROP TABLE "hawb"."other_charge"`);
        await queryRunner.query(`DROP TYPE "hawb"."other_charge_type_enum"`);
        await queryRunner.query(`DROP TABLE "hawb"."billing"`);
        await queryRunner.query(`DROP TABLE "hawb"."hawb_accounting"`);
        await queryRunner.query(`DROP TABLE "hawb"."hawb_dimension"`);
        await queryRunner.query(`DROP TABLE "hawb"."hawb_agent"`);
        await queryRunner.query(`DROP TABLE "common"."consignee"`);
        await queryRunner.query(`DROP TABLE "mawb"."agent"`);
        await queryRunner.query(`DROP TABLE "mawb"."dimension"`);
        await queryRunner.query(`DROP TABLE "mawb"."accounting"`);
        await queryRunner.query(`DROP TABLE "user"."users"`);
        await queryRunner.query(`DROP TYPE "user"."users_role_enum"`);
    }

}
