import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1778084350248 implements MigrationInterface {
    name = 'Init1778084350248'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "mawb"."airport" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "departure" character varying(50) NOT NULL, "destination" character varying(50) NOT NULL, "to" character(3) NOT NULL, "by_first_carrier" character(2) NOT NULL, "second_to" character(3), "second_by" character(2), "third_to" character(3), "third_by" character(2), "flight_date" date NOT NULL, "mawbId" integer, CONSTRAINT "REL_b1bf4ca0ede25cc2bd35cf0f9d" UNIQUE ("mawbId"), CONSTRAINT "PK_ea1ecba8dec9bee0cb60194e788" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hawb"."hawb_airport" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "departure" character varying(50) NOT NULL, "destination" character varying(50) NOT NULL, "to" character(3) NOT NULL, "by_first_carrier" character(2) NOT NULL, "second_to" character(3), "second_by" character(2), "third_to" character(3), "third_by" character(2), "flight_date" date NOT NULL, "hawbId" integer, CONSTRAINT "REL_4e0f4798704bdb38f70bb9d301" UNIQUE ("hawbId"), CONSTRAINT "PK_643ff3faafb63d0c7b2ea8c20dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."hawb_nature_of_goods" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "title" character varying(100) NOT NULL, "detail" character varying(100) NOT NULL, "hawbId" integer, CONSTRAINT "PK_7e691b763ad533ce6c48fe6e07a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "common"."agent" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "name" character varying(100) NOT NULL, "alias" character varying(100), "IATA_code" character varying(20), "email" character varying(100), "po_box_number" character varying(20), "phone_number" character varying(20), "office_number" character varying(20), "address" character varying(255) NOT NULL, "city" character varying(255) NOT NULL, "country" character varying(255) NOT NULL, CONSTRAINT "UQ_9a9b77c86fb1156b826d1b93c2a" UNIQUE ("name"), CONSTRAINT "UQ_c8e51500f3876fa1bbd4483ecc1" UNIQUE ("email"), CONSTRAINT "PK_1000e989398c5d4ed585cf9a46f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mawb"."nature_of_goods" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP, "title" character varying(100) NOT NULL, "detail" character varying(100) NOT NULL, "mawbId" integer, CONSTRAINT "PK_d5c0812defac584308650e2d36c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "signature"`);
        await queryRunner.query(`CREATE TYPE "hawb"."hawb_dimension_unit_enum" AS ENUM('CM', 'M', 'IN', 'FT', 'MM')`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "dimension_unit" "hawb"."hawb_dimension_unit_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "account_no" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "agent_id" integer`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "city_name" character varying(100)`);
        await queryRunner.query(`CREATE TYPE "mawb"."mawb_dimension_unit_enum" AS ENUM('CM', 'M', 'IN', 'FT', 'MM')`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "dimension_unit" "mawb"."mawb_dimension_unit_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "account_no" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "agent_id" integer`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP COLUMN "reference_number"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD "reference_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD "currency" character(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP COLUMN "chgs_code"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD "chgs_code" character(2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ALTER COLUMN "declared_value_carriage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ALTER COLUMN "declared_value_customs" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ALTER COLUMN "insurance_amt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP COLUMN "length"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD "length" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP COLUMN "width"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD "width" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP COLUMN "height"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD "height" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "common"."consignee" ALTER COLUMN "po_box_number" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP COLUMN "length"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD "length" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP COLUMN "width"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD "width" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP COLUMN "height"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD "height" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" DROP COLUMN "chgs_code"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ADD "chgs_code" character(2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ALTER COLUMN "declared_value_carriage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ALTER COLUMN "declared_value_customs" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ALTER COLUMN "insurance_amt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "weight_charge"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "weight_charge" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "valuation_charge"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "valuation_charge" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "tax"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "tax" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "total_charge_agent"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "total_charge_agent" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "total_charge_carrier"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "total_charge_carrier" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "total"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "total" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "signature"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "signature" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "executed_date"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "executed_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "place"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "place" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."other_charge" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "hawb"."other_charge" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "information"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "information" text`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "note" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "unit"`);
        await queryRunner.query(`CREATE TYPE "hawb"."hawb_unit_enum" AS ENUM('KG', 'LB')`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "unit" "hawb"."hawb_unit_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "rate_class"`);
        await queryRunner.query(`CREATE TYPE "hawb"."hawb_rate_class_enum" AS ENUM('N', 'Q', 'B', 'C', 'R', 'S', 'U', 'M', 'E')`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "rate_class" "hawb"."hawb_rate_class_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "commodity_item_no"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "commodity_item_no" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ALTER COLUMN "rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ALTER COLUMN "total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "weight_charge"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "weight_charge" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "valuation_charge"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "valuation_charge" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "tax"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "tax" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "total_charge_agent"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "total_charge_agent" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "total_charge_carrier"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "total_charge_carrier" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "total"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "total" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "executed_date"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "executed_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "place"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "place" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."other_charge" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "mawb"."other_charge" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "airline_prefix"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "airline_prefix" character(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "serial_no"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "serial_no" character(7) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "check_digit"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "check_digit" character(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "information"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "information" text`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "note" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "unit"`);
        await queryRunner.query(`CREATE TYPE "mawb"."mawb_unit_enum" AS ENUM('KG', 'LB')`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "unit" "mawb"."mawb_unit_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "rate_class"`);
        await queryRunner.query(`CREATE TYPE "mawb"."mawb_rate_class_enum" AS ENUM('N', 'Q', 'B', 'C', 'R', 'S', 'U', 'M', 'E')`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "rate_class" "mawb"."mawb_rate_class_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "commodity_item_no"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "commodity_item_no" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "common"."shipper" ALTER COLUMN "po_box_number" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."airport" ADD CONSTRAINT "FK_b1bf4ca0ede25cc2bd35cf0f9d0" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_airport" ADD CONSTRAINT "FK_4e0f4798704bdb38f70bb9d3015" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."hawb_nature_of_goods" ADD CONSTRAINT "FK_d4fb7bb819af849f24566f78175" FOREIGN KEY ("hawbId") REFERENCES "hawb"."hawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD CONSTRAINT "FK_3223deecab9b4b8249d0ccde205" FOREIGN KEY ("agent_id") REFERENCES "common"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."nature_of_goods" ADD CONSTRAINT "FK_df0f2a90436f875e1c6c7ad1091" FOREIGN KEY ("mawbId") REFERENCES "mawb"."mawb"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD CONSTRAINT "FK_d1349a34cee6a25f4f9f24d544e" FOREIGN KEY ("agent_id") REFERENCES "common"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP CONSTRAINT "FK_d1349a34cee6a25f4f9f24d544e"`);
        await queryRunner.query(`ALTER TABLE "mawb"."nature_of_goods" DROP CONSTRAINT "FK_df0f2a90436f875e1c6c7ad1091"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP CONSTRAINT "FK_3223deecab9b4b8249d0ccde205"`);
        await queryRunner.query(`ALTER TABLE "mawb"."hawb_nature_of_goods" DROP CONSTRAINT "FK_d4fb7bb819af849f24566f78175"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_airport" DROP CONSTRAINT "FK_4e0f4798704bdb38f70bb9d3015"`);
        await queryRunner.query(`ALTER TABLE "mawb"."airport" DROP CONSTRAINT "FK_b1bf4ca0ede25cc2bd35cf0f9d0"`);
        await queryRunner.query(`ALTER TABLE "common"."shipper" ALTER COLUMN "po_box_number" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "commodity_item_no"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "commodity_item_no" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "rate_class"`);
        await queryRunner.query(`DROP TYPE "mawb"."mawb_rate_class_enum"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "rate_class" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "unit"`);
        await queryRunner.query(`DROP TYPE "mawb"."mawb_unit_enum"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "unit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "information"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "information" character varying`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "check_digit"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "check_digit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "serial_no"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "serial_no" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "airline_prefix"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" ADD "airline_prefix" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."other_charge" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "mawb"."other_charge" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "place"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "place" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "executed_date"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "executed_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "total"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "total" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "total_charge_carrier"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "total_charge_carrier" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "total_charge_agent"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "total_charge_agent" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "tax"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "tax" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "valuation_charge"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "valuation_charge" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" DROP COLUMN "weight_charge"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "weight_charge" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ALTER COLUMN "total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ALTER COLUMN "rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "commodity_item_no"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "commodity_item_no" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "rate_class"`);
        await queryRunner.query(`DROP TYPE "hawb"."hawb_rate_class_enum"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "rate_class" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "unit"`);
        await queryRunner.query(`DROP TYPE "hawb"."hawb_unit_enum"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "unit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "information"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" ADD "information" character varying`);
        await queryRunner.query(`ALTER TABLE "hawb"."other_charge" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "hawb"."other_charge" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "place"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "place" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "executed_date"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "executed_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "signature"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "signature" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "total"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "total" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "total_charge_carrier"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "total_charge_carrier" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "total_charge_agent"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "total_charge_agent" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "tax"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "tax" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "valuation_charge"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "valuation_charge" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" DROP COLUMN "weight_charge"`);
        await queryRunner.query(`ALTER TABLE "hawb"."billing" ADD "weight_charge" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ALTER COLUMN "insurance_amt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ALTER COLUMN "declared_value_customs" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ALTER COLUMN "declared_value_carriage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" DROP COLUMN "chgs_code"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_accounting" ADD "chgs_code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP COLUMN "height"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD "height" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP COLUMN "width"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD "width" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" DROP COLUMN "length"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb_dimension" ADD "length" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "common"."consignee" ALTER COLUMN "po_box_number" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP COLUMN "height"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD "height" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP COLUMN "width"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD "width" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" DROP COLUMN "length"`);
        await queryRunner.query(`ALTER TABLE "mawb"."dimension" ADD "length" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ALTER COLUMN "insurance_amt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ALTER COLUMN "declared_value_customs" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ALTER COLUMN "declared_value_carriage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP COLUMN "chgs_code"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD "chgs_code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD "currency" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" DROP COLUMN "reference_number"`);
        await queryRunner.query(`ALTER TABLE "mawb"."accounting" ADD "reference_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "agent_id"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "account_no"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "dimension_unit"`);
        await queryRunner.query(`DROP TYPE "mawb"."mawb_dimension_unit_enum"`);
        await queryRunner.query(`ALTER TABLE "mawb"."mawb" DROP COLUMN "city_name"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "agent_id"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "account_no"`);
        await queryRunner.query(`ALTER TABLE "hawb"."hawb" DROP COLUMN "dimension_unit"`);
        await queryRunner.query(`DROP TYPE "hawb"."hawb_dimension_unit_enum"`);
        await queryRunner.query(`ALTER TABLE "mawb"."billing" ADD "signature" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "mawb"."nature_of_goods"`);
        await queryRunner.query(`DROP TABLE "common"."agent"`);
        await queryRunner.query(`DROP TABLE "mawb"."hawb_nature_of_goods"`);
        await queryRunner.query(`DROP TABLE "hawb"."hawb_airport"`);
        await queryRunner.query(`DROP TABLE "mawb"."airport"`);
    }

}
